/** Zoek-/spraaktermen die nooit naar een zaaknaam mogen worden gecorrigeerd. */
export const PROTECTED_SEARCH_VOCABULARY = new Set([
  'frituur',
  'friet',
  'frites',
  'frieten',
  'friture',
  'frituurzaak',
  'kebab',
  'kebap',
  'pizza',
  'pizzeria',
  'snack',
  'snackbar',
  'restaurant',
  'resto',
  'traiteur',
  'broodjeszaak',
  'broodjes',
  'sushi',
  'chinees',
  'bistro',
  'bakkerij',
  'bakker',
  'bakkers',
  'bakkerszaak',
  'slagerij',
  'slager',
  'slagers',
  'beenhouwer',
  'beenhouwen',
  'beenhouwerij',
  'beenhouwers',
  'vleeswinkel',
  'patisserie',
  'charcuterie',
  'koffiehuis',
  'lunchroom',
  'foodtruck',
  'foodtrucks',
  'ijssalon',
  'ijssalons',
  'wijnhandel',
  'wijnwinkel',
  'kassa',
  'kassasysteem',
  'kassasystemen',
  'pos',
  'diensten',
  'dienst',
  'leverancier',
  'leveranciers',
  'publiciteit',
  'meubilair',
  'inrichting',
  'groothandel',
  'vysion',
  'ordervysion',
  'café',
  'cafe',
  'dichtbij',
  'antwerpen',
  'lier',
  'turnhout',
  'mechelen',
  'gent',
  'hasselt',
  'pelt',
  'genk',
  'leuven',
  'brussel',
  'brugge',
])

const SEARCH_TOKEN_ALIASES: Record<string, string> = {
  frites: 'frituur',
  frite: 'frituur',
  bakker: 'bakkerij',
  bakkers: 'bakkerij',
  bakkerszaak: 'bakkerij',
  slager: 'slagerij',
  slagers: 'slagerij',
  beenhouwer: 'slagerij',
  beenhouwen: 'slagerij',
  beenhouwerij: 'slagerij',
  beenhouwers: 'slagerij',
  vleeswinkel: 'slagerij',
}

/** STT/typo → canonieke zoekterm (type zaak). */
export function canonicalizeSearchToken(token: string): string {
  const t = token.toLowerCase()
  return SEARCH_TOKEN_ALIASES[t] ?? token
}
