-- Anon/authenticated mogen pin_hash en name_normalized niet lezen (PIN-offline-aanval).
-- Service role blijft volledige toegang. Voer dit script uit in Supabase SQL Editor als migratie 017.

REVOKE ALL ON TABLE public.gids_listings FROM anon, authenticated;

GRANT SELECT (
  id,
  slug,
  name,
  status,
  type,
  cuisine_type,
  city,
  postcode,
  province,
  address,
  order_url,
  menu_url,
  menu_pdf_path,
  menu_pdf_public_url,
  menu_catalog_active,
  website,
  phone,
  email,
  opening_hours,
  closed_days,
  hours_by_day,
  amenities,
  rating_avg,
  rating_count,
  delivery_time_min,
  delivery_time_max,
  pickup_time_min,
  pickup_time_max,
  delivery_radius_km,
  delivery_fee_eur,
  min_order_eur,
  pickup_enabled,
  delivery_enabled,
  lat,
  lng,
  info_extras,
  premium_member,
  premium_paid_at,
  premium_expires_at,
  premium_paused,
  created_at,
  updated_at
) ON public.gids_listings TO anon, authenticated;
